name: Formatting and Clippy check

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  formating_and_clippy_check:
    name: Code Formating Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - name: format
            command: fmt --all -- --check
          - name: clippy
            command: clippy --all-targets --all-features
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: Run ${{ matrix.action.name }}
        run: cargo ${{ matrix.action.command }}
